name: corneliusio
favicon: null
layout_spectrum: 0.23314488912001252
typography_spectrum: 0.16116311121731997
title: Cornelius Ukena
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7237237587105483
  lightness: 0.3814250158611685
  saturation: 0.9616308186668903
  rhythmicContrast: 0.8643611415755004
purpose: []
