name: corneliusio
favicon: null
layout_spectrum: 0
typography_spectrum: 0.69506
title: Cornelius Ukena
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6da890'
    - '#8a7550'
    - '#ce9f00'
    - '#86120b'
    - '#001d74'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
