name: corneliusio
favicon: null
layout_spectrum: 0.25978
typography_spectrum: 0.69506
title: Cornelius Ukena
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#333333'
    - '#f53237'
    - '#b3b3b3'
    - '#000000'
  brandStrength: 1
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
